//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odev3.Kaynaklar {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dili {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dili() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Odev3.Kaynaklar.dili", typeof(dili).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Yarışmada dört kategori bulunmaktadır: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TÜRKSAT 5B uydusunu 19 Aralık sabah 06.58&apos;de SpaceX Falcon 9 roketiyle uzaya gönderiyoruz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a10 {
            get {
                return ResourceManager.GetString("a10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Astronotlar Uzayda! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a11 {
            get {
                return ResourceManager.GetString("a11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teknofest Kazananları! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a12 {
            get {
                return ResourceManager.GetString("a12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5B Uydusunu Uzaya Gönderiyoruz! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a13 {
            get {
                return ResourceManager.GetString("a13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bizi Takip Edin! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a14 {
            get {
                return ResourceManager.GetString("a14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İnstagram&apos;da bizi takip edin! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a15 {
            get {
                return ResourceManager.GetString("a15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Twitter&apos;da bizi takip edin! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a16 {
            get {
                return ResourceManager.GetString("a16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linkedin&apos;de bizi takip edin! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a17 {
            get {
                return ResourceManager.GetString("a17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub&apos;da bizi takip edin! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a18 {
            get {
                return ResourceManager.GetString("a18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROKET benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a19 {
            get {
                return ResourceManager.GetString("a19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lise Kategorisi (5.000 feet) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orta İrtifa Kategorisi (10.000 feet) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüksek İrtifa Kategorisi (20.000 feet) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zorlu Görev Kategorisi (10.000 feet) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yarışma kapsamında takımların; Ön Tasarım Raporu (ÖTR), Kritik Tasarım Raporu (KTR), Atış Hazırlık Raporu (AHR) olmak üzere 3 farklı rapor hazırlamaları gerekmektedir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a6 {
            get {
                return ResourceManager.GetString("a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roket Haberleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SpaceX, NASA&apos;nın &quot;Crew-3&quot; astronotlarını Uluslararası Uzay İstasyonuna ulaştırdı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roketsan&apos;ın TEKNOFEST kapsamındaki Roket Yarışması&apos;nın kazananları belli oldu! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string a9 {
            get {
                return ResourceManager.GetString("a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetici Paneli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adminPaneli {
            get {
                return ResourceManager.GetString("adminPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roket, mekanik anlamda bir jet motorunda olduğu gibi yanma işlemine bağlı olarak itki üreten ancak bunu yaparken çevreden mecburi bir hava 
        ///            girişine ihtiyaç duymayan motora verilen addır. Bir roket motoru kullanarak öz-itki üreten askerî ya da sivil amaçlı mermi, füze, uzay-hava araçlarının tamamına da roket denilebilir.TEKNOFEST Teknoloji yarışmaları kapsamında Roket Yarışması düzenlenmektedir.
        ///            Roket Yarışmanın amacı öğrencilerin uzay teknolojileri alanına ilgilerini arttırarak bu [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfayazi {
            get {
                return ResourceManager.GetString("anasayfayazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aviyonik Sistem benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AviyonikSistem {
            get {
                return ResourceManager.GetString("AviyonikSistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basınç Sensörleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BasincSensorleri {
            get {
                return ResourceManager.GetString("BasincSensorleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu sitenin tüm hakları Ayşegül Toptaş&apos;a aittir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üye Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kurtarma Sistemi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string KurtarmaSistemi {
            get {
                return ResourceManager.GetString("KurtarmaSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MİKROİŞLEMCİLER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m1 {
            get {
                return ResourceManager.GetString("m1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PWM Çıkışı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m10 {
            get {
                return ResourceManager.GetString("m10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ağırlık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m11 {
            get {
                return ResourceManager.GetString("m11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arduino, elektronik donanım ve yazılım temelli bir geliştirme platformudur.
        ///                Arduino Uno, en yaygın kullanılan ve en çok bilinen modelidir.
        ///                2010 yılında kullanıma sunulmuştur. Arduino Uno ile çeşitli sensörlerden fiziksel bilgi alabilir, bu bilgiler ile çeşitli deneyler yapabilirsiniz.
        ///                Ayrıca motor, LED, buzzer gibi uyarıcılardan bir çıktı elde edebilirsiniz.
        ///                Motorların hızı, LED’lerdeki parlaklık seviyeleri gibi analog olarak kontrol edilme [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m12 {
            get {
                return ResourceManager.GetString("m12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dijital Giriş/Çıkış Pini benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışma Gerilimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m14 {
            get {
                return ResourceManager.GetString("m14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arduino Nano ATmega328 mikrodenetleyici (Arduino Nano 3.x) veya Atmega168 (Arduino Nano 2.x) mikrodenetleyici barındıran, küçük, tam ve breadboard dostu bir Arduino kartıdır.
        ///                Arduino Nano bir B tipi mini USB kablosu ile bilgisayar bağlanarak çalıştırılabilir ya da harici bir güç kaynağından beslenebilir. 6-20 V aralığında bir harici güç kaynağı pin 30&apos;a bağlanabilir ya da 5 V regüle edilmiş bir gerilim ile pin 27 den beslenebilir.
        ///                Arduino Nano &apos;da bulunan 14 tane dijital gi [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m15 {
            get {
                return ResourceManager.GetString("m15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LED Sayısı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m16 {
            get {
                return ResourceManager.GetString("m16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push Buton benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m17 {
            get {
                return ResourceManager.GetString("m17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güç Kaynağı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m18 {
            get {
                return ResourceManager.GetString("m18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STM32F407 kısaca 168 Mhz saat frekansına sahip 32-bit’lik bir mikrodenetleyicidir.
        ///                Özellikle DSP uygulamalarında , içerisinde bir çok alt sistemler olan yapıların ana beyni olarak kullanılmaktadır.
        ///                Üzerinde STM32F4VG çekirdeğini barındırmaktadır.
        ///                3-eksen ivme ölçer , dahili ses girişi ve buna bağlı dijital analog dönüştürücü , 4 adet programlanabilir LED , 2 adet buton barındırır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m19 {
            get {
                return ResourceManager.GetString("m19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikroişlemci nedir? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m2 {
            get {
                return ResourceManager.GetString("m2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teensy 3.6, küçük boylu ve breadboard uyumlu bir geliştirme kartıdır. 32-bit ARM Cortex-M4 platformuna sahiptir. Arduino IDE&apos;nin modifiye edilmiş bir versiyonu (Teensyduino) ile kolay bir şekilde programlama imkanı sunar. Teensy 3.6, 3.2 ve 3.5 sürümlerinin güncellenmiş ve daha fazla işlem gücü sunan en son Teensy sürümüdür.
        ///
        ///                    3.6 sürümü, kayan nokta ünitesi (floating point unit) içeren 32-bit 180MHz ARM Cortex-M4 işlemciye sahiptir. Tüm dijital ve analog girişler 3.3V seviyesinde çalış [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m20 {
            get {
                return ResourceManager.GetString("m20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikroişlemci, mantıksal ve aritmetik işlemler yapabilen ve bu işlemlerin neticesine bağlı olarak çalışmasını yönlendirebilen tümleşik bir devre elemanıdır. Bulundukları elektronik yapıların beyni olan mikroişlemciler, bağlı oldukları mekanizmanın kontrolünü sağlarlar. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m3 {
            get {
                return ResourceManager.GetString("m3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikroişlemci seçilirken nelere dikkat edilmelidir? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m4 {
            get {
                return ResourceManager.GetString("m4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikroişlemci seçimleri kullanılacak yazılım diline uygun olacak şekilde yapılmalıdır. Kullanılacak sistem için yeterli sayıda giriş-çıkış pini bulunması ve işlemci gücünün yeterli olması seçim yapılırken dikkat edilmesi gereken noktalardır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m5 {
            get {
                return ResourceManager.GetString("m5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikroişlemci Çeşitleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m6 {
            get {
                return ResourceManager.GetString("m6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Özellik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m7 {
            get {
                return ResourceManager.GetString("m7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dijital Çıkış Pini benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m8 {
            get {
                return ResourceManager.GetString("m8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analog Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string m9 {
            get {
                return ResourceManager.GetString("m9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mekanik Sistem benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MekanikSistem {
            get {
                return ResourceManager.GetString("MekanikSistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merhaba benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string merhaba {
            get {
                return ResourceManager.GetString("merhaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mikroişlemciler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mikroislemciler {
            get {
                return ResourceManager.GetString("Mikroislemciler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üye Girişi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string oturumac {
            get {
                return ResourceManager.GetString("oturumac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oturumu Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string oturumkapa {
            get {
                return ResourceManager.GetString("oturumkapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıcaklık Sensörleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SicaklikSensorleri {
            get {
                return ResourceManager.GetString("SicaklikSensorleri", resourceCulture);
            }
        }
    }
}
